# Generated by Django 5.1.7 on 2025-03-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likes',
        ),
    ]
