# Generated by Django 5.1.7 on 2025-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_homeopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeopinion',
            name='thoughts',
            field=models.TextField(),
        ),
    ]
