# Generated by Django 5.1.7 on 2025-04-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_homeopinion_thoughts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeopinion',
            unique_together={('user',)},
        ),
    ]
