# Generated by Django 5.1.7 on 2025-04-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_homeopinion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeopinion',
            unique_together=set(),
        ),
    ]
