# Generated by Django 5.1.7 on 2025-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_homeopinion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('char_name', models.CharField(max_length=255)),
                ('anime_name', models.CharField(max_length=255)),
                ('opinion', models.TextField()),
                ('thoughts', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
