# Generated by Django 5.1.7 on 2025-04-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imgdatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgdatabase',
            old_name='img_url',
            new_name='char_img_url',
        ),
    ]
