# Generated by Django 5.1.7 on 2025-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_img_url_imgdatabase_char_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgdatabase',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='imgdatabase',
            name='agree',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='imgdatabase',
            name='disagree',
            field=models.TextField(default=0),
        ),
    ]
