# Generated by Django 5.1.7 on 2025-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_imgdatabase_thoughts_imgdatabase_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdatabase',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imgdatabase',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
    ]
