# Generated by Django 5.1.7 on 2025-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_imgdatabase_agree_alter_imgdatabase_disagree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeopinion',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='homeopinion',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeopinion',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
    ]
