# Generated by Django 5.1.7 on 2025-04-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_homeopinion_thoughts_homeopinion_agree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOpinionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=10)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.homeopinion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'opinion')},
            },
        ),
    ]
